# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 852dd345529ba0c083af2ed02bf075a0f0d642de5651c1234061265dc5d1ff3af8e2b4351a01bbe391ea031378b6b56a53d1051854f544f93cf07880b19b997c

test:
  secret_key_base: 5ae5b088e6cdade4765b06d2527e3dbab3f2b52a4faed605cceb133a495e4615449b7586557d2edb9d6f71e4b4c40809a37f9de30afc60917991411b676883e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
